apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-worker
  template:
    metadata:
      labels:
        app: mlops-worker
    spec:
      containers:
      - name: mlops-worker
        image: uicheolhwang/mlops-worker:0.0.1
