apiVersion: batch/v1
kind: Job
metadata:
  name: data-generator-job
spec:
  template:
    spec:
      containers:
      - name: data-generator
        image: asia-northeast3-docker.pkg.dev/cheorish/docker/model-create
        command: ["/bin/bash", "-c"]
        args: ["./run_scripts.sh"]
        env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: mydatabase
      restartPolicy: Never
  backoffLimit: 0
