apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - name: postgres-server
        image: postgres:14.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: targetuser  # PostgreSQL 사용자 이름
        - name: POSTGRES_PASSWORD
          value: targetpassword  # PostgreSQL 암호
        - name: POSTGRES_DB
          value: targetdatabase  # PostgreSQL 데이터베이스 이름
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-target-database
spec:
  selector:
    app: postgres-server
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP 

