apiVersion: batch/v1
kind: Job
metadata:
  name: mlflow-model-training
spec:
  template:
    spec:
      containers:
      - name: model-trainer
        image: asia-northeast3-docker.pkg.dev/cheorish/docker/model-save # 빌드한 이미지
        env:
          - name: POSTGRES_USER
            value: "myuser"
          - name: POSTGRES_PASSWORD
            value: "mypassword"
          # 추가 환경 변수
      restartPolicy: Never