apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow
        image: asia-northeast3-docker.pkg.dev/cheorish/docker/mlflow
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "miniostorage"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://mlflow-artifact-store:9000"
        - name: BACKEND_STORE_URI
          value: "postgresql://mlflowuser:mlflowpassword@mlflow-backend-store/mlflowdatabase"
        - name: DEFAULT_ARTIFACT_ROOT
          value: "s3://mlflow/"
        command: ["/bin/sh", "-c"]
        args: ["mc config host add mlflowminio http://mlflow-artifact-store:9000 minio miniostorage && mc mb --ignore-existing mlflowminio/mlflow && mlflow server --backend-store-uri postgresql://mlflowuser:mlflowpassword@mlflow-backend-store/mlflowdatabase --default-artifact-root s3://mlflow/ --host 0.0.0.0"]

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mlflow-server
