apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  ports:
  - port: 5000
  selector:
    app: mlflow-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow
        image: gcr.io/[PROJECT-ID]/mlflow-server:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minio"
        - name: AWS_SECRET_ACCESS_KEY
          value: "miniostorage"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://mlflow-artifact-store:9000"
        ports:
        - containerPort: 5000
