apiVersion: v1
kind: Service
metadata:
  name: mlflow-backend-store
  namespace: mlflow
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: mlflow-backend-store

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-backend-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-backend-store
  template:
    metadata:
      labels:
        app: mlflow-backend-store
    spec:
      containers:
      - name: postgres
        image: postgres:14.0
        env:
        - name: POSTGRES_USER
          value: "mlflowuser"
        - name: POSTGRES_PASSWORD
          value: "mlflowpassword"
        - name: POSTGRES_DB
          value: "mlflowdatabase"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: mlflow-backend-pvc
          mountPath: /var/lib/postgresql/data 
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mlflowuser
            - -d
            - mlflowdatabase
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 5

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 