name: deployment-pipeline

on:
  push:
    branches:
      - master
    # 특정 파드 생성 전 오류가 났을 시 비상망으로 운영하는 CI
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Google Cloud
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
        run: |
          echo $GCP_KEY | cat > ./key.json
          cat ./key.json | docker login -u _json_key --password-stdin asia-northeast3-docker.pkg.dev

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin


      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd /usr/local/bin/argocd
          sudo chmod +x /usr/local/bin/argocd
          rm argocd

      - name: Login to Argo CD
        env:
          ARGOCD_IP: ${{ secrets.ARGOCD_IP }}
          ARGOCD_ID: ${{ secrets.ARGOCD_ID }}
          ARGOCD_PW: ${{ secrets.ARGOCD_PW }}
        run: |
          argocd login $ARGOCD_IP --username $ARGOCD_ID --password $ARGOCD_PW --insecure

      - name: Update Argo CD App
        run: |
          # 기존 애플리케이션에 새로운 경로 추가
          argocd app set worker --repo https://github.com/UICHEOL-HWANG/mlops-practices.git --path config --dest-namespace worker

